#!/bin/ksh -l

set +x
source /lfs/h2/emc/vpppg/noscrub/${USER}/gefsv12/versions/run.ver
module purge
module load envvar/${envvar_ver}
module load intel/${intel_ver}
module load PrgEnv-intel/${PrgEnvintel_ver}
module load craype/${craype_ver}
module load cray-mpich/${craympich_ver}
module load cray-pals/${craypals_ver}
module load prod_util/${prod_util_ver}
module load prod_envir/${prod_envir_ver}
module load libjpeg/${libjpeg_ver}
module load grib_util/${grib_util_ver}
module load wgrib2/${wgrib2_ver}
module load cfp/${cfp_ver}
#Load Python
module load python/${python_ver}
module load proj/${proj_ver}
module load geos/${geos_ver}
module use /lfs/h1/mdl/nbm/save/apps/modulefiles
module unload python-modules/3.8.6
module load grib2io/${grib2io_ver}
export PYTHONPATH="${PYTHONPATH}:/lfs/h2/emc/vpppg/noscrub/${USER}/python"

#module list
set -x

cyc=$1

mkdir -p /lfs/h2/emc/stmp/${USER}/cron.out
mkdir -p /lfs/h2/emc/stmp/${USER}/gefsv12
cd /lfs/h2/emc/stmp/${USER}/gefsv12
cp /lfs/h2/emc/vpppg/noscrub/${USER}/gefsv12/*gfsxsta*txt .
cp /lfs/h2/emc/vpppg/noscrub/${USER}/gefsv12/matplotlibrc .
cp /lfs/h2/emc/vpppg/noscrub/${USER}/gefsv12/EMCGEFSplumes.html .

sleep 3
/bin/date +%Y%m%d${cyc}%a > holddate.txt
sleep 3
/bin/date --date="yesterday" +%Y%m%d${cyc}%a > yholddate.txt

#sleep 3
#/bin/date --date="yesterday" +%Y%m%d${cyc}%a > holddate.txt
#sleep 3
#/bin/date --date="2 days ago" +%Y%m%d${cyc}%a > yholddate.txt

sleep 3
qsub /lfs/h2/emc/vpppg/noscrub/${USER}/gefsv12/run_gefs
exit
