#!/bin/ksh --login
echo 'into'
source /lfs/h2/emc/vpppg/noscrub/${USER}/gefsv12/versions/run.ver
module purge
module load envvar/${envvar_ver}
module load intel/${intel_ver}
module load PrgEnv-intel/${PrgEnvintel_ver}
module load craype/${craype_ver}
module load cray-mpich/${craympich_ver}
module load cray-pals/${craypals_ver}
module load prod_util/${prod_util_ver}
module load prod_envir/${prod_envir_ver}
module load libjpeg/${libjpeg_ver}
module load grib_util/${grib_util_ver}
module load wgrib2/${wgrib2_ver}
module load cfp/${cfp_ver}
#Load Python
module load python/${python_ver}
module load proj/${proj_ver}
module load geos/${geos_ver}
module use /lfs/h1/mdl/nbm/save/apps/modulefiles
module unload python-modules/3.8.6
module load grib2io/${grib2io_ver}
export PYTHONPATH="${PYTHONPATH}:/lfs/h2/emc/vpppg/noscrub/${USER}/python"

#module list
cyc=$1

cd /lfs/h2/emc/stmp/${USER}/gefsv12


year=`cut -c 1-4 holddate.txt`
month=`cut -c 5-6 holddate.txt`
day=`cut -c 7-8 holddate.txt`
hour=`cut -c 9-10 holddate.txt`
dow=`cut -c 11-13 holddate.txt`
ymdh=${year}${month}${day}${hour}
ymdhdow=${year}${month}${day}${hour}${dow}


python /lfs/h2/emc/vpppg/noscrub/${USER}/gefsv12/makegefs2mtcsv.py $ymdh > out_2mt_python.txt &
python /lfs/h2/emc/vpppg/noscrub/${USER}/gefsv12/makegefs2mdewcsv.py $ymdh > out_2mdew_python.txt &
python /lfs/h2/emc/vpppg/noscrub/${USER}/gefsv12/makegefscapecsv.py $ymdh > out_cape_python.txt &
python /lfs/h2/emc/vpppg/noscrub/${USER}/gefsv12/makegefsslpcsv.py $ymdh > out_slp_python.txt &
wait


cp /lfs/h2/emc/vpppg/noscrub/${USER}/gefsv12/edit_gefs.ksh .
./edit_gefs.ksh

exit


