#!/bin/ksh --login
echo 'into'
module purge
#source /u/Alicia.Bentley/.bashrc
module load ips/18.0.1.163
module load impi/18.0.1
module load NetCDF/4.5.0
module load bacio/2.0.2
module load sfcio/1.0.0
module load lsf/10.1
module load nemsio/2.2.3
module load w3emc/2.3.0
module load sp/2.0.2
module load w3nco/2.0.6
module load impi/18.0.1
module load bufr/11.2.0
module load sigio/2.0.1
module load crtm/2.2.5
module load CFP/2.0.1
module load EnvVars/1.0.2
module load pm5/1.0
module load subversion/1.7.16
module load HPSS/5.0.2.5
module load mktgs/1.0
module load rsync/3.1.2
module load ip/3.0.1
module load prod_envir/1.0.2
module load grib_util/1.0.6
module load prod_util/1.1.5

module load python/3.6.3
module use /gpfs/dell2/mdl/mdlstat/save/util/modulefiles
module load python-extra/3.6.3
#module use -a /u/Benjamin.Blake/modulefiles
#module load python3/test
#export GRIB_DEFINITION_PATH=/usrx/local/nceplibs/dev/lib/grib_api/share/grib_api/definitions

export PYTHONPATH=${PYTHONPATH}:/gpfs/dell2/emc/modeling/noscrub/Jacob.Carley/python/lib/python3.6/site-packages
cyc=$1

mkdir -p /gpfs/dell1/stmp/Alicia.Bentley/grib2io_test
cd /gpfs/dell1/stmp/Alicia.Bentley/grib2io_test
cp /gpfs/dell2/emc/verification/save/Alicia.Bentley/grib2io_test/matplotlibrc .
cp /gpfs/dell2/emc/verification/save/Alicia.Bentley/grib2io_test/EMCGEFSplumes.html .


year=`cut -c 1-4 holddate.txt`
month=`cut -c 5-6 holddate.txt`
day=`cut -c 7-8 holddate.txt`
hour=`cut -c 9-10 holddate.txt`
dow=`cut -c 11-13 holddate.txt`
ymdh=${year}${month}${day}${hour}
ymdhdow=${year}${month}${day}${hour}${dow}


#python /gpfs/dell2/emc/verification/save/Alicia.Bentley/grib2io_test/makegefscsv.py $ymdh &
#python /gpfs/dell2/emc/verification/save/Alicia.Bentley/grib2io_test/makegefsqpfcsv.py $ymdh > out_qpf_python.txt &
#python /gpfs/dell2/emc/verification/save/Alicia.Bentley/grib2io_test/makegefs3hqpfcsv.py $ymdh > out_3hqpf_python.txt &
#python /gpfs/dell2/emc/verification/save/Alicia.Bentley/grib2io_test/makegefs2mtcsv.py $ymdh > out_2mt_python.txt &
#python /gpfs/dell2/emc/verification/save/Alicia.Bentley/grib2io_test/makegefs2mdewcsv.py $ymdh > out_2mdew_python.txt &
#python /gpfs/dell2/emc/verification/save/Alicia.Bentley/grib2io_test/makegefs2mrhcsv.py $ymdh > out_2mrh_python.txt &
#python /gpfs/dell2/emc/verification/save/Alicia.Bentley/grib2io_test/makegefs10mwindcsv.py $ymdh > out_10mwind_python.txt &
#python /gpfs/dell2/emc/verification/save/Alicia.Bentley/grib2io_test/makegefs850tcsv.py $ymdh > out_850t_python.txt &
#python /gpfs/dell2/emc/verification/save/Alicia.Bentley/grib2io_test/makegefs850windcsv.py $ymdh > out_850wind_python.txt &
#python /gpfs/dell2/emc/verification/save/Alicia.Bentley/grib2io_test/makegefspwcsv.py $ymdh > out_pw_python.txt &
python /gpfs/dell2/emc/verification/save/Alicia.Bentley/grib2io_test/makegefscapecsv.py $ymdh > out_cape_python.txt &
#python /gpfs/dell2/emc/verification/save/Alicia.Bentley/grib2io_test/makegefsshearcsv.py $ymdh > out_shear_python.txt &
#python /gpfs/dell2/emc/verification/save/Alicia.Bentley/grib2io_test/makegefssnowcsv.py $ymdh > out_snow_python.txt &
#python /gpfs/dell2/emc/verification/save/Alicia.Bentley/grib2io_test/makegefsptypecsv.py $ymdh > out_ptype_python.txt &
#python /gpfs/dell2/emc/verification/save/Alicia.Bentley/grib2io_test/makegefsthickcsv.py $ymdh > out_thick_python.txt &
#python /gpfs/dell2/emc/verification/save/Alicia.Bentley/grib2io_test/makegefsslpcsv.py $ymdh > out_slp_python.txt &
wait


cp /gpfs/dell2/emc/verification/save/Alicia.Bentley/grib2io_test/edit_gefs.ksh .
./edit_gefs.ksh

exit


