#!/bin/bash
#PBS -N gefs.ftp
#PBS -o /lfs/h2/emc/ptmp/Alicia.Bentley/cron.out/gefsftp1.out
#PBS -e /lfs/h2/emc/ptmp/Alicia.Bentley/cron.out/gefsftp1.err
#PBS -l select=1:ncpus=4:mem=1GB
#PBS -q dev_transfer
#PBS -l walltime=00:10:00
#PBS -A VERF-DEV

set -x

cd /lfs/h2/emc/stmp/Alicia.Bentley/gefsv12

cyc=`cut -c 9-10 holddate.txt`
day=`cut -c 7-8 holddate.txt`
echo $day

pwd

ls -l

ls -l *csv

pwd

scp *2m*csv abentley@emcrzdm:/home/www/emc/htdocs/users/meg/grib2io_test
scp *qpf*csv abentley@emcrzdm:/home/www/emc/htdocs/users/meg/grib2io_test
scp *shear*csv abentley@emcrzdm:/home/www/emc/htdocs/users/meg/grib2io_test
scp *thick*csv abentley@emcrzdm:/home/www/emc/htdocs/users/meg/grib2io_test
scp *slp*csv abentley@emcrzdm:/home/www/emc/htdocs/users/meg/grib2io_test

exit

