#!/bin/bash
#PBS -N gefs.ftp2
#PBS -o /lfs/h2/emc/stmp/alicia.bentley/cron.out/gefsftp2.out
#PBS -e /lfs/h2/emc/stmp/alicia.bentley/cron.out/gefsftp2.err
#PBS -l select=1:ncpus=10:mem=2GB
#PBS -q dev_transfer
#PBS -l walltime=02:00:00
#PBS -A VERF-DEV

set -x

cd /lfs/h2/emc/stmp/${USER}/gefsv12

cyc=`cut -c 9-10 holddate.txt`
day=`cut -c 7-8 holddate.txt`
echo $day

pwd

ls -l

ls -l *csv

pwd

scp *pw*csv abentley@emcrzdm:/home/www/emc/htdocs/users/meg/gefs_plumes 
scp *cape*csv abentley@emcrzdm:/home/www/emc/htdocs/users/meg/gefs_plumes
scp *850*csv abentley@emcrzdm:/home/www/emc/htdocs/users/meg/gefs_plumes


exit

