#! /bin/ksh
#
#BSUB -J wafs.ftp
#BSUB -oo /gpfs/dell2/emc/verification/save/Alicia.Bentley/grib2io_test/gefsftp.out
#BSUB -eo /gpfs/dell2/emc/verification/save/Alicia.Bentley/grib2io_test/gefsftp.out
#BSUB -n 1
#BSUB -W 00:10
#BSUB -P GEN-T2O
#BSUB -R "affinity[core]"
#BSUB -q dev_transfer
#BSUB -R "rusage[mem=300]"

set -x

cd /gpfs/dell1/stmp/Alicia.Bentley/grib2io_test

cyc=`cut -c 9-10 holddate.txt`
day=`cut -c 7-8 holddate.txt`
echo $day
number=$(ls -l * | grep csv | wc -l)

pwd

ls -l

ls -l *csv

pwd

scp *pw*csv abentley@emcrzdm:/home/www/emc/htdocs/users/meg/grib2io_test 
scp *850*csv abentley@emcrzdm:/home/www/emc/htdocs/users/meg/grib2io_test
scp *cape*csv abentley@emcrzdm:/home/www/emc/htdocs/users/meg/grib2io_test
scp *10m*csv abentley@emcrzdm:/home/www/emc/htdocs/users/meg/grib2io_test
scp *typ*csv abentley@emcrzdm:/home/www/emc/htdocs/users/meg/grib2io_test 
scp *snow*csv abentley@emcrzdm:/home/www/emc/htdocs/users/meg/grib2io_test 

#if [[ $number -gt 3700 ]];then
  scp EMC*html abentley@emcrzdm:/home/www/emc/htdocs/users/meg/grib2io_test/index.html
#fi

exit

